name: PullPrompt

on:
  pull_request: # Works only on pull requests

jobs:
  pull_prompt:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Required for reading files
      pull-requests: write # Required for commenting on PRs

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Running PullPrompt
        uses: Pradumnasaraf/pullprompt@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Required
          user-prompt: "Share an open-source tip in 2 to 3 lines to help developers improve their workflow"
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }} # Required
