name: PullPrompt

on:
  pull_request: # Works only on pull requests

jobs:
  pull_prompt:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Required for reading files
      pull-requests: write # Required for commenting on PRs

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Running PullPrompt
        uses: Pradumnasaraf/pullprompt@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Required
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }} # Required
          user-prompt: "Tell me about America"
          character-limit: 500 # Optional
